/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author aashi
 */
public class ItemPage extends javax.swing.JFrame {

    /**
     * Creates new form ItemPage
     */
    Connection conn;
    ResultSet rs;
    
    String user,pname,pid;
    String prod,seller,deliv;
    int price;
    public ItemPage(String st, String name) {
        initComponents();
        //user=st;
        pname=name;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/aidkart","root","aashish2000");
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ItemPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        System.out.println("Name:"+name);
        l2.setIcon(new javax.swing.ImageIcon("C:\\Users\\aashi\\Desktop\\5th Sem\\OOAD Lab\\Images\\"+name+".jpg"));
        
        
        
        
        System.out.println(user);
        l1.setText(st);
        
        if("Guest Mode".equals(st))
        {
            user="Guest Mode";
        }
        else
        {
            user=st.split("\\s")[1];
        }
        
        //ImageIcon ic=new ImageIcon(getClass().getResource("C:\\Users\\aashi\\Documents\\NetBeansProjects\\AidKart\\src\\main\\java\\Tissot Women.jpg"));
        //l2.setIcon(new ImageIcon("/Images/Casio.jpg"));
        
        
        Statement s;
        int i=0;
        try {
            s = conn.createStatement();
            rs=s.executeQuery("select * from products where pname="+"'"+name+"'");

            while(rs.next())
            {
                pid=rs.getString("pid");
                prod=rs.getString("pname");
                price=rs.getInt("price");
                seller=rs.getString("seller");
                deliv=rs.getString("delivery");
                l3.setText(l3.getText()+rs.getString("pname"));
                ta1.setText(rs.getString("description"));
                l4.setText(l4.getText()+Integer.toString(rs.getInt("price")));
                l5.setText(l5.getText()+rs.getString("seller"));
                l6.setText(l6.getText()+rs.getString("delivery"));
                l7.setText(l7.getText()+rs.getString("ptype"));
            }
            
            System.out.println(i);
        } catch (SQLException ex) {
            Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta1 = new javax.swing.JTextArea();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        l2 = new javax.swing.JLabel();
        l7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel12.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("                              AidKart");
        jLabel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel12);
        jLabel12.setBounds(70, 0, 970, 50);

        l1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        l1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        l1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l1MouseClicked(evt);
            }
        });
        getContentPane().add(l1);
        l1.setBounds(1070, 0, 170, 50);

        l6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l6.setText("Delivery: ");
        l6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(l6);
        l6.setBounds(830, 380, 210, 40);

        ta1.setEditable(false);
        ta1.setColumns(20);
        ta1.setRows(5);
        jScrollPane1.setViewportView(ta1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(530, 140, 510, 80);

        l3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l3.setText("Name: ");
        l3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(l3);
        l3.setBounds(530, 70, 510, 40);

        l4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l4.setText("Price:  ");
        l4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(l4);
        l4.setBounds(680, 250, 210, 40);

        l5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l5.setText("Seller: ");
        l5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(l5);
        l5.setBounds(540, 380, 210, 40);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1090, 480, 130, 40);

        jButton2.setText("Add to Cart");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(720, 480, 140, 40);

        l2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(l2);
        l2.setBounds(75, 74, 390, 470);

        l7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l7.setText("Type: ");
        l7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(l7);
        l7.setBounds(1010, 250, 210, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        setExtendedState(ItemPage.MAXIMIZED_BOTH); 
    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Statement s;
        int i=0;
        int qty=0;
        if(!"Guest Mode".equals(user))
        {
            try {
                s = conn.createStatement();
                rs=s.executeQuery("select * from cart where pname='"+pname+"' and username='"+user+"'");
            while(rs.next())
            {
                qty=rs.getInt("qty");
                i+=1;                
            }
            
            
            } catch (SQLException ex) {
                Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            if(i==0)
            {
                try {
                    String query="Insert into cart values(?,?,?,?,?,?,?)";
                    PreparedStatement stmt=conn.prepareStatement(query);

                    stmt.setString(1,user);
                    stmt.setString(2,prod);
                    stmt.setString(5,deliv);
                    stmt.setString(4,seller);
                    stmt.setInt(3,price);
                    stmt.setString(6,pid);
                    stmt.setInt(7,1);
                
                    stmt.execute();

                
                } catch (SQLException ex) {
                    Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
            else
            {
                try {
                    String query="Update cart set qty="+Integer.toString(qty+1)+" where pname='"+pname+"' and username='"+user+"'";
                    PreparedStatement stmt=conn.prepareStatement(query);

                    stmt.execute();

                
                } catch (SQLException ex) {
                    Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }            
            JOptionPane.showMessageDialog(this, "Added To Cart");
        }
        else
        {
            JOptionPane.showMessageDialog(this,"You Must Login Before adding item to cart!");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ProductPage frame;
        if("Guest Mode".equals(user))
        {
            frame=new ProductPage("NULL");
        }
        else
        {
            frame=new ProductPage(user);
        }
        
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void l1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l1MouseClicked
        // TODO add your handling code here:
        if(!l1.getText().equals("Guest Mode"))
        {
            Cart c=new Cart(user);
            c.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_l1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ItemPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ItemPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ItemPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ItemPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ItemPage("Guest Mode","").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l7;
    private javax.swing.JTextArea ta1;
    // End of variables declaration//GEN-END:variables
}
