
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author aashi
 */
public class SellPage extends javax.swing.JFrame {

    /**
     * Creates new form SellPage
     */
    String user;
    ArrayList<String> det=new ArrayList<>();
    int mulid;
    Connection conn;
    ResultSet rs;
    public SellPage(String st,ArrayList<String> arr,int mul) {
        initComponents();
        mulid=mul;
        
        System.out.println("Welcome: "+st);
        if(!"NULL".equals(st))
            l1.setText("Hi "+st);
        else
            l1.setText("Guest Mode");
        
        user=st;
        
        
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/aidkart","root","aashish2000");
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ItemPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        try {
            Statement s;
            String query="Select * from products where pid like 'U%' and seller='"+user+"'";
            s=conn.createStatement();
            int i=1;
            rs=s.executeQuery(query);
            
            while(rs.next())
            {
                if(i==1)
                {
                    p1.setIcon(new javax.swing.ImageIcon(rs.getString("image")));
                    b1.setText(rs.getString("pname"));
                }
                if(i==2)
                {
                    p2.setIcon(new javax.swing.ImageIcon(rs.getString("image")));
                    b2.setText(rs.getString("pname"));
                }
                if(i==3)
                {
                    p3.setIcon(new javax.swing.ImageIcon(rs.getString("image")));
                    b3.setText(rs.getString("pname"));
                }
                if(i==4)
                {
                    p4.setIcon(new javax.swing.ImageIcon(rs.getString("image")));
                    b4.setText(rs.getString("pname"));
                }
                if(i==5)
                {
                    p5.setIcon(new javax.swing.ImageIcon(rs.getString("image")));
                    b5.setText(rs.getString("pname"));
                }
                if(i==6)
                {
                    p6.setIcon(new javax.swing.ImageIcon(rs.getString("image")));
                    b6.setText(rs.getString("pname"));
                }
                if(i==7)
                {
                    p7.setIcon(new javax.swing.ImageIcon(rs.getString("image")));
                    b7.setText(rs.getString("pname"));
                }
                if(i==8)
                {
                    p8.setIcon(new javax.swing.ImageIcon(rs.getString("image")));
                    b8.setText(rs.getString("pname"));
                }
                
                i++;
            }
                        
            
        } catch (SQLException ex) {
            Logger.getLogger(Cart.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void Items(String val,int no)
    {
        det.add(Integer.toString(no));
        det.add("");
        det.add("");
        AddItemPage it=new AddItemPage(user,det,mulid);
        it.setVisible(true);
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton9 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        b1 = new javax.swing.JButton();
        p1 = new javax.swing.JLabel();
        b2 = new javax.swing.JButton();
        p2 = new javax.swing.JLabel();
        b3 = new javax.swing.JButton();
        p3 = new javax.swing.JLabel();
        b4 = new javax.swing.JButton();
        p4 = new javax.swing.JLabel();
        b8 = new javax.swing.JButton();
        p8 = new javax.swing.JLabel();
        b7 = new javax.swing.JButton();
        p7 = new javax.swing.JLabel();
        b6 = new javax.swing.JButton();
        p6 = new javax.swing.JLabel();
        b5 = new javax.swing.JButton();
        p5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jButton9.setText("Back to Home");
        jButton9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(50, 10, 140, 30);

        jLabel12.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("  AidKart");
        jLabel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel12);
        jLabel12.setBounds(220, 0, 820, 50);

        l1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        l1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        l1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l1MouseClicked(evt);
            }
        });
        getContentPane().add(l1);
        l1.setBounds(1070, 0, 190, 50);

        jPanel1.setLayout(null);

        b1.setText("Add Item");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        jPanel1.add(b1);
        b1.setBounds(100, 240, 190, 23);

        p1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(p1);
        p1.setBounds(100, 10, 190, 280);

        b2.setText("Add Item");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        jPanel1.add(b2);
        b2.setBounds(380, 240, 190, 23);

        p2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(p2);
        p2.setBounds(380, 10, 190, 280);

        b3.setText("Add Item");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        jPanel1.add(b3);
        b3.setBounds(660, 240, 190, 23);

        p3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(p3);
        p3.setBounds(660, 10, 190, 280);

        b4.setText("Add Item");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        jPanel1.add(b4);
        b4.setBounds(940, 240, 190, 23);

        p4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(p4);
        p4.setBounds(940, 10, 190, 280);

        b8.setText("Add Item");
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });
        jPanel1.add(b8);
        b8.setBounds(940, 540, 190, 23);

        p8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(p8);
        p8.setBounds(940, 310, 190, 280);

        b7.setText("Add Item");
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });
        jPanel1.add(b7);
        b7.setBounds(660, 540, 190, 23);

        p7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(p7);
        p7.setBounds(660, 310, 190, 280);

        b6.setText("Add Item");
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        jPanel1.add(b6);
        b6.setBounds(380, 540, 190, 23);

        p6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(p6);
        p6.setBounds(380, 310, 190, 280);

        b5.setText("Add Item");
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        jPanel1.add(b5);
        b5.setBounds(100, 540, 190, 23);

        p5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(p5);
        p5.setBounds(100, 310, 190, 280);

        jScrollPane1.setViewportView(jPanel1);

        jTabbedPane1.addTab("Sell Products", jScrollPane1);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(50, 50, 1210, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        Home page=new Home();
        page.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void l1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l1MouseClicked
        // TODO add your handling code here:
        if(!l1.getText().equals("Guest Mode"))
        {
            Cart c=new Cart(user);
            c.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_l1MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        setExtendedState(SellPage.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        Items(b1.getText(),1);
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
        Items(b2.getText(),2);
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
        Items(b3.getText(),3);
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
        Items(b4.getText(),4);
    }//GEN-LAST:event_b4ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        // TODO add your handling code here:
        Items(b8.getText(),8);
    }//GEN-LAST:event_b8ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        // TODO add your handling code here:
        Items(b7.getText(),7);
    }//GEN-LAST:event_b7ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        // TODO add your handling code here:
        Items(b6.getText(),6);
    }//GEN-LAST:event_b6ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        // TODO add your handling code here:
        Items(b5.getText(),5);
    }//GEN-LAST:event_b5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SellPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SellPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SellPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SellPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ArrayList<String> arr = new ArrayList<>(Arrays.asList("","",""));
                new SellPage("",arr,1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel p1;
    private javax.swing.JLabel p2;
    private javax.swing.JLabel p3;
    private javax.swing.JLabel p4;
    private javax.swing.JLabel p5;
    private javax.swing.JLabel p6;
    private javax.swing.JLabel p7;
    private javax.swing.JLabel p8;
    // End of variables declaration//GEN-END:variables
}
